/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DoctorId = IDL.Nat;
export const Doctor = IDL.Record({
  'doctorId' : DoctorId,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'specialty' : IDL.Text,
  'department' : IDL.Text,
});
export const FacilityStatus = IDL.Variant({
  'occupied' : IDL.Null,
  'available' : IDL.Null,
  'maintenance' : IDL.Null,
});
export const FacilityId = IDL.Nat;
export const Facility = IDL.Record({
  'status' : FacilityStatus,
  'name' : IDL.Text,
  'facilityId' : FacilityId,
  'location' : IDL.Text,
});
export const MedicineId = IDL.Nat;
export const Medicine = IDL.Record({
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'usage' : IDL.Text,
  'quantity' : IDL.Nat,
  'medicineId' : MedicineId,
});
export const Day = IDL.Variant({
  'fri' : IDL.Null,
  'mon' : IDL.Null,
  'sat' : IDL.Null,
  'sun' : IDL.Null,
  'thu' : IDL.Null,
  'tue' : IDL.Null,
  'wed' : IDL.Null,
});
export const PatientStatus = IDL.Variant({
  'discharged' : IDL.Null,
  'admitted' : IDL.Null,
});
export const PatientId = IDL.Nat;
export const Patient = IDL.Record({
  'status' : PatientStatus,
  'patientId' : PatientId,
  'admitDay' : Day,
  'name' : IDL.Text,
  'ward' : IDL.Text,
  'qrToken' : IDL.Text,
  'admitDate' : IDL.Text,
  'admitTime' : IDL.Text,
});
export const TreatmentId = IDL.Nat;
export const Treatment = IDL.Record({
  'patientId' : PatientId,
  'notes' : IDL.Text,
  'treatmentId' : TreatmentId,
  'treatmentDate' : IDL.Text,
  'treatmentType' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'totalPatients' : IDL.Nat,
  'totalFacilities' : IDL.Nat,
  'totalScans' : IDL.Nat,
  'totalTreatments' : IDL.Nat,
  'totalDoctors' : IDL.Nat,
  'totalMedicines' : IDL.Nat,
});
export const Time = IDL.Int;
export const LogId = IDL.Nat;
export const VisitorLog = IDL.Record({
  'logId' : LogId,
  'qrToken' : IDL.Text,
  'timestamp' : Time,
  'patientName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDoctor' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Doctor],
      [],
    ),
  'createFacility' : IDL.Func(
      [IDL.Text, IDL.Text, FacilityStatus],
      [Facility],
      [],
    ),
  'createMedicine' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [Medicine],
      [],
    ),
  'createPatient' : IDL.Func(
      [IDL.Text, IDL.Text, Day, IDL.Text, IDL.Text],
      [Patient],
      [],
    ),
  'createTreatment' : IDL.Func(
      [PatientId, IDL.Text, IDL.Text, IDL.Text],
      [Treatment],
      [],
    ),
  'deleteDoctor' : IDL.Func([DoctorId], [], []),
  'deleteFacility' : IDL.Func([FacilityId], [], []),
  'deleteMedicine' : IDL.Func([MedicineId], [], []),
  'deletePatient' : IDL.Func([PatientId], [], []),
  'deleteTreatment' : IDL.Func([TreatmentId], [], []),
  'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'getAllFacilities' : IDL.Func([], [IDL.Vec(Facility)], ['query']),
  'getAllMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getAllPatientsByName' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getAllTreatments' : IDL.Func([], [IDL.Vec(Treatment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getLastBackupTimestamp' : IDL.Func([], [Time], ['query']),
  'getPatientByQrToken' : IDL.Func([IDL.Text], [IDL.Opt(Patient)], []),
  'getTotalScans' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisitorLog' : IDL.Func([], [IDL.Vec(VisitorLog)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'triggerBackup' : IDL.Func([], [], []),
  'updateDoctor' : IDL.Func(
      [
        DoctorId,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateFacility' : IDL.Func(
      [
        FacilityId,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(FacilityStatus),
      ],
      [],
      [],
    ),
  'updateMedicine' : IDL.Func(
      [
        MedicineId,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updatePatient' : IDL.Func(
      [
        PatientId,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(Day),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(PatientStatus),
      ],
      [],
      [],
    ),
  'updateTreatment' : IDL.Func(
      [TreatmentId, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DoctorId = IDL.Nat;
  const Doctor = IDL.Record({
    'doctorId' : DoctorId,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'specialty' : IDL.Text,
    'department' : IDL.Text,
  });
  const FacilityStatus = IDL.Variant({
    'occupied' : IDL.Null,
    'available' : IDL.Null,
    'maintenance' : IDL.Null,
  });
  const FacilityId = IDL.Nat;
  const Facility = IDL.Record({
    'status' : FacilityStatus,
    'name' : IDL.Text,
    'facilityId' : FacilityId,
    'location' : IDL.Text,
  });
  const MedicineId = IDL.Nat;
  const Medicine = IDL.Record({
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'usage' : IDL.Text,
    'quantity' : IDL.Nat,
    'medicineId' : MedicineId,
  });
  const Day = IDL.Variant({
    'fri' : IDL.Null,
    'mon' : IDL.Null,
    'sat' : IDL.Null,
    'sun' : IDL.Null,
    'thu' : IDL.Null,
    'tue' : IDL.Null,
    'wed' : IDL.Null,
  });
  const PatientStatus = IDL.Variant({
    'discharged' : IDL.Null,
    'admitted' : IDL.Null,
  });
  const PatientId = IDL.Nat;
  const Patient = IDL.Record({
    'status' : PatientStatus,
    'patientId' : PatientId,
    'admitDay' : Day,
    'name' : IDL.Text,
    'ward' : IDL.Text,
    'qrToken' : IDL.Text,
    'admitDate' : IDL.Text,
    'admitTime' : IDL.Text,
  });
  const TreatmentId = IDL.Nat;
  const Treatment = IDL.Record({
    'patientId' : PatientId,
    'notes' : IDL.Text,
    'treatmentId' : TreatmentId,
    'treatmentDate' : IDL.Text,
    'treatmentType' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'totalPatients' : IDL.Nat,
    'totalFacilities' : IDL.Nat,
    'totalScans' : IDL.Nat,
    'totalTreatments' : IDL.Nat,
    'totalDoctors' : IDL.Nat,
    'totalMedicines' : IDL.Nat,
  });
  const Time = IDL.Int;
  const LogId = IDL.Nat;
  const VisitorLog = IDL.Record({
    'logId' : LogId,
    'qrToken' : IDL.Text,
    'timestamp' : Time,
    'patientName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDoctor' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Doctor],
        [],
      ),
    'createFacility' : IDL.Func(
        [IDL.Text, IDL.Text, FacilityStatus],
        [Facility],
        [],
      ),
    'createMedicine' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [Medicine],
        [],
      ),
    'createPatient' : IDL.Func(
        [IDL.Text, IDL.Text, Day, IDL.Text, IDL.Text],
        [Patient],
        [],
      ),
    'createTreatment' : IDL.Func(
        [PatientId, IDL.Text, IDL.Text, IDL.Text],
        [Treatment],
        [],
      ),
    'deleteDoctor' : IDL.Func([DoctorId], [], []),
    'deleteFacility' : IDL.Func([FacilityId], [], []),
    'deleteMedicine' : IDL.Func([MedicineId], [], []),
    'deletePatient' : IDL.Func([PatientId], [], []),
    'deleteTreatment' : IDL.Func([TreatmentId], [], []),
    'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'getAllFacilities' : IDL.Func([], [IDL.Vec(Facility)], ['query']),
    'getAllMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getAllPatientsByName' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getAllTreatments' : IDL.Func([], [IDL.Vec(Treatment)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getLastBackupTimestamp' : IDL.Func([], [Time], ['query']),
    'getPatientByQrToken' : IDL.Func([IDL.Text], [IDL.Opt(Patient)], []),
    'getTotalScans' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisitorLog' : IDL.Func([], [IDL.Vec(VisitorLog)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'triggerBackup' : IDL.Func([], [], []),
    'updateDoctor' : IDL.Func(
        [
          DoctorId,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateFacility' : IDL.Func(
        [
          FacilityId,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(FacilityStatus),
        ],
        [],
        [],
      ),
    'updateMedicine' : IDL.Func(
        [
          MedicineId,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updatePatient' : IDL.Func(
        [
          PatientId,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(Day),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(PatientStatus),
        ],
        [],
        [],
      ),
    'updateTreatment' : IDL.Func(
        [TreatmentId, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };