/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'totalPatients' : bigint,
  'totalFacilities' : bigint,
  'totalScans' : bigint,
  'totalTreatments' : bigint,
  'totalDoctors' : bigint,
  'totalMedicines' : bigint,
}
export type Day = { 'fri' : null } |
  { 'mon' : null } |
  { 'sat' : null } |
  { 'sun' : null } |
  { 'thu' : null } |
  { 'tue' : null } |
  { 'wed' : null };
export interface Doctor {
  'doctorId' : DoctorId,
  'contact' : string,
  'name' : string,
  'specialty' : string,
  'department' : string,
}
export type DoctorId = bigint;
export interface Facility {
  'status' : FacilityStatus,
  'name' : string,
  'facilityId' : FacilityId,
  'location' : string,
}
export type FacilityId = bigint;
export type FacilityStatus = { 'occupied' : null } |
  { 'available' : null } |
  { 'maintenance' : null };
export type LogId = bigint;
export interface Medicine {
  'name' : string,
  'unit' : string,
  'usage' : string,
  'quantity' : bigint,
  'medicineId' : MedicineId,
}
export type MedicineId = bigint;
export interface Patient {
  'status' : PatientStatus,
  'patientId' : PatientId,
  'admitDay' : Day,
  'name' : string,
  'ward' : string,
  'qrToken' : string,
  'admitDate' : string,
  'admitTime' : string,
}
export type PatientId = bigint;
export type PatientStatus = { 'discharged' : null } |
  { 'admitted' : null };
export type Time = bigint;
export interface Treatment {
  'patientId' : PatientId,
  'notes' : string,
  'treatmentId' : TreatmentId,
  'treatmentDate' : string,
  'treatmentType' : string,
}
export type TreatmentId = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VisitorLog {
  'logId' : LogId,
  'qrToken' : string,
  'timestamp' : Time,
  'patientName' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDoctor' : ActorMethod<[string, string, string, string], Doctor>,
  'createFacility' : ActorMethod<[string, string, FacilityStatus], Facility>,
  'createMedicine' : ActorMethod<[string, bigint, string, string], Medicine>,
  'createPatient' : ActorMethod<[string, string, Day, string, string], Patient>,
  'createTreatment' : ActorMethod<
    [PatientId, string, string, string],
    Treatment
  >,
  'deleteDoctor' : ActorMethod<[DoctorId], undefined>,
  'deleteFacility' : ActorMethod<[FacilityId], undefined>,
  'deleteMedicine' : ActorMethod<[MedicineId], undefined>,
  'deletePatient' : ActorMethod<[PatientId], undefined>,
  'deleteTreatment' : ActorMethod<[TreatmentId], undefined>,
  'getAllDoctors' : ActorMethod<[], Array<Doctor>>,
  'getAllFacilities' : ActorMethod<[], Array<Facility>>,
  'getAllMedicines' : ActorMethod<[], Array<Medicine>>,
  'getAllPatients' : ActorMethod<[], Array<Patient>>,
  'getAllPatientsByName' : ActorMethod<[], Array<Patient>>,
  'getAllTreatments' : ActorMethod<[], Array<Treatment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getLastBackupTimestamp' : ActorMethod<[], Time>,
  'getPatientByQrToken' : ActorMethod<[string], [] | [Patient]>,
  'getTotalScans' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisitorLog' : ActorMethod<[], Array<VisitorLog>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'triggerBackup' : ActorMethod<[], undefined>,
  'updateDoctor' : ActorMethod<
    [DoctorId, [] | [string], [] | [string], [] | [string], [] | [string]],
    undefined
  >,
  'updateFacility' : ActorMethod<
    [FacilityId, [] | [string], [] | [string], [] | [FacilityStatus]],
    undefined
  >,
  'updateMedicine' : ActorMethod<
    [MedicineId, [] | [string], [] | [bigint], [] | [string], [] | [string]],
    undefined
  >,
  'updatePatient' : ActorMethod<
    [
      PatientId,
      [] | [string],
      [] | [string],
      [] | [Day],
      [] | [string],
      [] | [string],
      [] | [PatientStatus],
    ],
    undefined
  >,
  'updateTreatment' : ActorMethod<
    [TreatmentId, [] | [string], [] | [string], [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];