/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export type DoctorId = bigint;
export type FacilityId = bigint;
export interface Facility {
    status: FacilityStatus;
    name: string;
    facilityId: FacilityId;
    location: string;
}
export type PatientId = bigint;
export type TreatmentId = bigint;
export interface Patient {
    status: PatientStatus;
    patientId: PatientId;
    admitDay: Day;
    name: string;
    ward: string;
    qrToken: string;
    admitDate: string;
    admitTime: string;
}
export type LogId = bigint;
export interface DashboardStats {
    totalPatients: bigint;
    totalFacilities: bigint;
    totalScans: bigint;
    totalTreatments: bigint;
    totalDoctors: bigint;
    totalMedicines: bigint;
}
export interface VisitorLog {
    logId: LogId;
    qrToken: string;
    timestamp: Time;
    patientName: string;
}
export type MedicineId = bigint;
export interface Medicine {
    name: string;
    unit: string;
    usage: string;
    quantity: bigint;
    medicineId: MedicineId;
}
export interface Doctor {
    doctorId: DoctorId;
    contact: string;
    name: string;
    specialty: string;
    department: string;
}
export interface Treatment {
    patientId: PatientId;
    notes: string;
    treatmentId: TreatmentId;
    treatmentDate: string;
    treatmentType: string;
}
export interface UserProfile {
    name: string;
}
export enum Day {
    fri = "fri",
    mon = "mon",
    sat = "sat",
    sun = "sun",
    thu = "thu",
    tue = "tue",
    wed = "wed"
}
export enum FacilityStatus {
    occupied = "occupied",
    available = "available",
    maintenance = "maintenance"
}
export enum PatientStatus {
    discharged = "discharged",
    admitted = "admitted"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createDoctor(name: string, specialty: string, department: string, contact: string): Promise<Doctor>;
    createFacility(name: string, location: string, status: FacilityStatus): Promise<Facility>;
    createMedicine(name: string, quantity: bigint, unit: string, usage: string): Promise<Medicine>;
    createPatient(name: string, admitDate: string, admitDay: Day, admitTime: string, ward: string): Promise<Patient>;
    createTreatment(patientId: PatientId, treatmentType: string, notes: string, treatmentDate: string): Promise<Treatment>;
    deleteDoctor(doctorId: DoctorId): Promise<void>;
    deleteFacility(facilityId: FacilityId): Promise<void>;
    deleteMedicine(medicineId: MedicineId): Promise<void>;
    deletePatient(patientId: PatientId): Promise<void>;
    deleteTreatment(treatmentId: TreatmentId): Promise<void>;
    getAllDoctors(): Promise<Array<Doctor>>;
    getAllFacilities(): Promise<Array<Facility>>;
    getAllMedicines(): Promise<Array<Medicine>>;
    getAllPatients(): Promise<Array<Patient>>;
    getAllPatientsByName(): Promise<Array<Patient>>;
    getAllTreatments(): Promise<Array<Treatment>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getLastBackupTimestamp(): Promise<Time>;
    getPatientByQrToken(qrToken: string): Promise<Patient | null>;
    getTotalScans(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVisitorLog(): Promise<Array<VisitorLog>>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    triggerBackup(): Promise<void>;
    updateDoctor(doctorId: DoctorId, name: string | null, specialty: string | null, department: string | null, contact: string | null): Promise<void>;
    updateFacility(facilityId: FacilityId, name: string | null, location: string | null, status: FacilityStatus | null): Promise<void>;
    updateMedicine(medicineId: MedicineId, name: string | null, quantity: bigint | null, unit: string | null, usage: string | null): Promise<void>;
    updatePatient(patientId: PatientId, name: string | null, admitDate: string | null, admitDay: Day | null, admitTime: string | null, ward: string | null, status: PatientStatus | null): Promise<void>;
    updateTreatment(treatmentId: TreatmentId, treatmentType: string | null, notes: string | null, treatmentDate: string | null): Promise<void>;
}
import type { Day as _Day, Facility as _Facility, FacilityId as _FacilityId, FacilityStatus as _FacilityStatus, Patient as _Patient, PatientId as _PatientId, PatientStatus as _PatientStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createDoctor(arg0: string, arg1: string, arg2: string, arg3: string): Promise<Doctor> {
        if (this.processError) {
            try {
                const result = await this.actor.createDoctor(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDoctor(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createFacility(arg0: string, arg1: string, arg2: FacilityStatus): Promise<Facility> {
        if (this.processError) {
            try {
                const result = await this.actor.createFacility(arg0, arg1, to_candid_FacilityStatus_n3(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Facility_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFacility(arg0, arg1, to_candid_FacilityStatus_n3(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Facility_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createMedicine(arg0: string, arg1: bigint, arg2: string, arg3: string): Promise<Medicine> {
        if (this.processError) {
            try {
                const result = await this.actor.createMedicine(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMedicine(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createPatient(arg0: string, arg1: string, arg2: Day, arg3: string, arg4: string): Promise<Patient> {
        if (this.processError) {
            try {
                const result = await this.actor.createPatient(arg0, arg1, to_candid_Day_n9(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return from_candid_Patient_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPatient(arg0, arg1, to_candid_Day_n9(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return from_candid_Patient_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTreatment(arg0: PatientId, arg1: string, arg2: string, arg3: string): Promise<Treatment> {
        if (this.processError) {
            try {
                const result = await this.actor.createTreatment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTreatment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteDoctor(arg0: DoctorId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDoctor(arg0);
            return result;
        }
    }
    async deleteFacility(arg0: FacilityId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFacility(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFacility(arg0);
            return result;
        }
    }
    async deleteMedicine(arg0: MedicineId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedicine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedicine(arg0);
            return result;
        }
    }
    async deletePatient(arg0: PatientId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePatient(arg0);
            return result;
        }
    }
    async deleteTreatment(arg0: TreatmentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTreatment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTreatment(arg0);
            return result;
        }
    }
    async getAllDoctors(): Promise<Array<Doctor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDoctors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDoctors();
            return result;
        }
    }
    async getAllFacilities(): Promise<Array<Facility>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFacilities();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFacilities();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMedicines(): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMedicines();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMedicines();
            return result;
        }
    }
    async getAllPatients(): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPatients();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPatients();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPatientsByName(): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPatientsByName();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPatientsByName();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTreatments(): Promise<Array<Treatment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTreatments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTreatments();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getLastBackupTimestamp(): Promise<Time> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastBackupTimestamp();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastBackupTimestamp();
            return result;
        }
    }
    async getPatientByQrToken(arg0: string): Promise<Patient | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientByQrToken(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientByQrToken(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalScans(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalScans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalScans();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisitorLog(): Promise<Array<VisitorLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisitorLog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisitorLog();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async triggerBackup(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.triggerBackup();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.triggerBackup();
            return result;
        }
    }
    async updateDoctor(arg0: DoctorId, arg1: string | null, arg2: string | null, arg3: string | null, arg4: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDoctor(arg0, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDoctor(arg0, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateFacility(arg0: FacilityId, arg1: string | null, arg2: string | null, arg3: FacilityStatus | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFacility(arg0, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFacility(arg0, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateMedicine(arg0: MedicineId, arg1: string | null, arg2: bigint | null, arg3: string | null, arg4: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMedicine(arg0, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMedicine(arg0, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updatePatient(arg0: PatientId, arg1: string | null, arg2: string | null, arg3: Day | null, arg4: string | null, arg5: string | null, arg6: PatientStatus | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePatient(arg0, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n27(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePatient(arg0, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n27(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async updateTreatment(arg0: TreatmentId, arg1: string | null, arg2: string | null, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTreatment(arg0, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTreatment(arg0, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_Day_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Day): Day {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_FacilityStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FacilityStatus): FacilityStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Facility_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Facility): Facility {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_PatientStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PatientStatus): PatientStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Patient_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Patient): Patient {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Patient]): Patient | null {
    return value.length === 0 ? null : from_candid_Patient_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PatientStatus;
    patientId: _PatientId;
    admitDay: _Day;
    name: string;
    ward: string;
    qrToken: string;
    admitDate: string;
    admitTime: string;
}): {
    status: PatientStatus;
    patientId: PatientId;
    admitDay: Day;
    name: string;
    ward: string;
    qrToken: string;
    admitDate: string;
    admitTime: string;
} {
    return {
        status: from_candid_PatientStatus_n13(_uploadFile, _downloadFile, value.status),
        patientId: value.patientId,
        admitDay: from_candid_Day_n15(_uploadFile, _downloadFile, value.admitDay),
        name: value.name,
        ward: value.ward,
        qrToken: value.qrToken,
        admitDate: value.admitDate,
        admitTime: value.admitTime
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _FacilityStatus;
    name: string;
    facilityId: _FacilityId;
    location: string;
}): {
    status: FacilityStatus;
    name: string;
    facilityId: FacilityId;
    location: string;
} {
    return {
        status: from_candid_FacilityStatus_n7(_uploadFile, _downloadFile, value.status),
        name: value.name,
        facilityId: value.facilityId,
        location: value.location
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    discharged: null;
} | {
    admitted: null;
}): PatientStatus {
    return "discharged" in value ? PatientStatus.discharged : "admitted" in value ? PatientStatus.admitted : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fri: null;
} | {
    mon: null;
} | {
    sat: null;
} | {
    sun: null;
} | {
    thu: null;
} | {
    tue: null;
} | {
    wed: null;
}): Day {
    return "fri" in value ? Day.fri : "mon" in value ? Day.mon : "sat" in value ? Day.sat : "sun" in value ? Day.sun : "thu" in value ? Day.thu : "tue" in value ? Day.tue : "wed" in value ? Day.wed : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    occupied: null;
} | {
    available: null;
} | {
    maintenance: null;
}): FacilityStatus {
    return "occupied" in value ? FacilityStatus.occupied : "available" in value ? FacilityStatus.available : "maintenance" in value ? FacilityStatus.maintenance : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Facility>): Array<Facility> {
    return value.map((x)=>from_candid_Facility_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Patient>): Array<Patient> {
    return value.map((x)=>from_candid_Patient_n11(_uploadFile, _downloadFile, x));
}
function to_candid_Day_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Day): _Day {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_FacilityStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FacilityStatus): _FacilityStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_PatientStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PatientStatus): _PatientStatus {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FacilityStatus | null): [] | [_FacilityStatus] {
    return value === null ? candid_none() : candid_some(to_candid_FacilityStatus_n3(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Day | null): [] | [_Day] {
    return value === null ? candid_none() : candid_some(to_candid_Day_n9(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PatientStatus | null): [] | [_PatientStatus] {
    return value === null ? candid_none() : candid_some(to_candid_PatientStatus_n28(_uploadFile, _downloadFile, value));
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Day): {
    fri: null;
} | {
    mon: null;
} | {
    sat: null;
} | {
    sun: null;
} | {
    thu: null;
} | {
    tue: null;
} | {
    wed: null;
} {
    return value == Day.fri ? {
        fri: null
    } : value == Day.mon ? {
        mon: null
    } : value == Day.sat ? {
        sat: null
    } : value == Day.sun ? {
        sun: null
    } : value == Day.thu ? {
        thu: null
    } : value == Day.tue ? {
        tue: null
    } : value == Day.wed ? {
        wed: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PatientStatus): {
    discharged: null;
} | {
    admitted: null;
} {
    return value == PatientStatus.discharged ? {
        discharged: null
    } : value == PatientStatus.admitted ? {
        admitted: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FacilityStatus): {
    occupied: null;
} | {
    available: null;
} | {
    maintenance: null;
} {
    return value == FacilityStatus.occupied ? {
        occupied: null
    } : value == FacilityStatus.available ? {
        available: null
    } : value == FacilityStatus.maintenance ? {
        maintenance: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
